CREATE TABLE ANIMAL(
Animal_name varchar(12) NOT NULL,
AnimalID char(6) NOT NULL,
AnimalCatogory varchar(12),
AnimalDOB date NOT null,
Jungle_Id char(5) NOT NULL ,

constraint DRIVER_ID PRIMARY KEY(AnimalID),
/*constraint Foriegn_key foreign key(Jungle_Id) REFERENCES JUNGLE(Jungle_Id) */
);

/*INSERT DATA TO THE TABLES*/
INSERT INTO ANIMAL VALUES ('Trnosorex' , 'DISO01' , 'Dinosours' , '2000-06-09' , 'dehi8' );
INSERT INTO ANIMAL VALUES ('Alasourex' , 'DISO02' , 'Dinosours' , '2000-12-09' , 'dehi8' );
INSERT INTO ANIMAL VALUES ('Eagle' , 'EIGO01' , 'Birds' , '1998-09-09' , 'dehi8' );

SELECT * 
FROM ANIMAL

CREATE TABLE JUNGLE (
JUNGLE_ID CHAR(5) NOT NULL,
JUNGLE_NAME VARCHAR(10) NOT NULL,
JUNGLE_LOCATED VARCHAR (20),
AnimalID char(6) NOT NULL,

CONSTRAINT PRIMARY_KEY PRIMARY KEY(JUNGLE_ID) ,
CONSTRAINT FOREIGN_KEY FOREIGN KEY(AnimalID) REFERENCES ANIMAL(AnimalID)
);

SELECT *
FROM JUNGLE

/*INSERT DATA INTO TABLES*/
INSERT INTO JUNGLE VALUES ( 'dehi8' , 'Frdom' , 'Dehiwala ' , 'DISO01' );
INSERT INTO JUNGLE VALUES ( 'dehi7' , 'Frdom' , 'Dehiwala ' , 'DISO01' );
INSERT INTO JUNGLE VALUES ( 'dehi6' , 'Frdom' , 'Dehiwala ' , 'DISO01');


select *
from JUNGLE

/*update data*/
UPDATE JUNGLE
SET JUNGLE_NAME = 'Siri Pura' , JUNGLE_LOCATED = 'Malasiya jort' 
WHERE JUNGLE_NAME ='Frdom' AND JUNGLE_ID ='dehi7'

SELECT *
FROM JUNGLE

UPDATE JUNGLE
SET JUNGLE_NAME = 'Komali' , JUNGLE_LOCATED = 'kasakasthan' 
where JUNGLE_ID = 'dehi6' 

SELECT *
FROM JUNGLE

/*DELETE ROWS IN THE DATABAES*/

DELETE FROM JUNGLE
WHERE JUNGLE_ID= 'dehi8'

SELECT *
FROM JUNGLE

INSERT INTO JUNGLE VALUES ('dehi1' , 'SUDO' , 'JAPAN TOKIYO' , 'DISO01' );
INSERT INTO JUNGLE VALUES ('dehi2' , 'SUDO' , 'JAPAN NAGASAKI' , 'DISO01' );
INSERT INTO JUNGLE VALUES ('dehi3' , 'KALI' , 'MAHARASHTA INDIA' , 'DISO02' );
INSERT INTO JUNGLE VALUES ('dehi4' , 'QUEEN' , 'BAKINHAM ENGLEAND' , 'EIGO01' );

SELECT * 
FROM JUNGLE

UPDATE JUNGLE
SET JUNGLE_NAME ='BOMB'
WHERE JUNGLE_ID = 'dehi8'

select *
from JUNGLE